[project]
name = "reading-big-files"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.6.0",
    "pandas>=2.3.3",
    "pydantic>=2.12.0",
]
