name: Compare Python scripts

on:
  push:
    branches: [main]
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9, 3.10, 3.12, 3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run benchmark
      run: |
        echo "Python version: $(python3 --version)"
        sh compare.sh

